version: '3.7'                                #specify docker-compose file format version
services:                                     #Define the services to be run
  meandemo_mongo:                             # name of service
    image: jhuopensource/meandemo:mongo
    build: 
      context: ./mongo                        #relative location of Dockerfile
    #ports:
      #- "27017:27017"                        #port mapping / expose from container
  meandemo_express_node:                      #name of service
    image: jhuopensource/meandemo:express_node
    build: 
      context: ./meandemo                     #relative location of Dockerfile
    #ports:
      #- "3000:3000"                          #port mapping / expose from container
      #- "4200:4200"                          #port mapping / expose from container
    depends_on:
      - meandemo_mongo                        #dependency service
  meandemo_nginx_angular_node:                #name of service
    image: jhuopensource/meandemo:nginx_angular_node
    build: 
      context: ./nginx                        #relative location of Dockerfile
    ports:
      - "8080:80"                             #port mapping / map the host port 8080 to container internal 80 running nginx
    depends_on:
      - meandemo_express_node                 #dependency service

  
